// This file has been generated by TypeSharpGen

export interface ImageTagsController {

    RemoveTag(imageId: number, tagId: number): Promise<void>;

    AddTag(id: number, tagId: number): Promise<void>;
}
